### ISSUE TITLE
Allow `extend-allowed-calls` for `algopy.GlobalState`

### ISSUE THREAD

**Issue by cusma** [algorandfoundation/algokit-python-template#26]
## Problem

Declaring a `bool` as `GlobalState` (e.g. ):

```python
self.foo = GlobalState(True, description="A boolean")
```
Raises the following error on linting: `FBT003 Boolean positional value in function call`

## Solution

Add the following Ruff config to `pyproject.toml` (@daniel-makerx):

```toml
[tool.ruff.lint.flake8-boolean-trap]
extend-allowed-calls = ["algopy.GlobalState"]
```

## Dependencies

Needs `ruff >= 0.3.5` (to be bumped in AlgoKit init requirements, as is currently set as `ruff = "^0.1.6"`).
